
variable "version" {
  type    = string
  default = "webserver"
}

source "amazon-ebs" "autogenerated_1" {
  access_key    = "AKIA44JKGJ"
  ami_name      = "${var.version}"
  instance_type = "t2.micro"
  region        = "us-west-2"
  secret_key    = "zSpolmjEf+XOQ1axB5YK"
  source_ami    = "ami-017fecd1353bcc96e"
  ssh_username  = "ubuntu"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    inline = ["sleep 30", "sudo apt-get update -y", "sudo apt-get install nginx -y"]
  }

  post-processor "manifest" {
    output = "manifest.json"
  }
}
