
source "amazon-ebs" "autogenerated_1" {
  access_key    = "AKIAJKGJ"
  ami_name      = "my-ubuntu-image-5"
  instance_type = "t2.micro"
  region        = "us-west-2"
  secret_key    = "zSpolBVU9AmjEf+XOQ1axB5YK"
  source_ami    = "ami-017fecd1353bcc96e"
  ssh_username  = "ubuntu"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    inline = ["sleep 30", "sudo apt-get update -y", "sudo apt-get install nginx -y"]
  }

  post-processor "manifest" {
    output = "manifest.json"
  }
}
