
variable "access_key" {
  type    = string
  default = "${env("ACCESS_KEY")}"
}

variable "secret_key" {
  type    = string
  default = "${env("SECRET_KEY")}"
}

source "amazon-ebs" "autogenerated_1" {
  access_key    = "${var.access_key}"
  ami_name      = "devops-image"
  instance_type = "t2.micro"
  region        = "us-west-2"
  secret_key    = "${var.secret_key}"
  source_ami    = "ami-017fecd1353bcc96e"
  ssh_username  = "ubuntu"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    inline = ["sleep 30", "sudo apt-get update -y", "sudo apt-get install nginx -y"]
  }

  post-processor "manifest" {
    output = "manifest.json"
  }
}
