
source "amazon-ebs" "autogenerated_1" {
  access_key    = "AKIA4OLNHDPVQ4SZB76P"
  ami_name      = "sample-image"
  instance_type = "t2.micro"
  region        = "us-west-2"
  secret_key    = "k6i7R38Sirub2Lbz2mwVBmmlXKXlCOhtf/HdM6Td"
  source_ami    = "ami-094125af156557ca2"
  ssh_username  = "ec2-user"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

}
