---
- name: sample handlers playbook
  hosts: webservers
  become: yes

  tasks:
    - name: installing httpd into webservers
      yum:
        name: httpd
        state: present
      notify: Start httpd
 
  handlers:
    - name: Start httpd
      service:
        name: httpd
        state: restarted

