---
- name: installing jenkins
  hosts: webservers
  become: true

  tasks:
    - name: install java software
      yum:
        name: java
        state: present

    - name: install wget software
      yum:
        name: wget
        state: present

    - name: download the jenkins software
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: download jenkins key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat/jenkins.io.key

    - name: install jenkins
      yum:
        name: jenkins
        state: installed

    - name: start the jenkins
      service:
        name: jenkins
        state: started
        enabled: yes
      
