---
- name: creating the sample loop
  hosts: webservers
  become: true

  tasks:
    - name: install package
      yum: name="{{item}}" state=present
      with_items: 
       - httpd
       - git
       - mysql
       - java
       - docker
        
