---
- name: creating simple handler
  hosts: webservers
  become: true
  tasks:  
    - name: installing httpd into webservers
      yum:
        name: httpd
        state: present
      notify: start httpd 

  handlers:     
  - name: start httpd
    service:
      name: httpd
      state: restarted

