---
- name : createing the sample variable
  hosts : webservers
  become : true
  
  vars: 
   pkgname: httpd

  tasks: 
   - name: install httpd into webserver
     yum:
       name: '{{pkgname}}'
       state: installed
